server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///D:/config-service1
  mvc:
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: Content-Type, Authorization      